SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;
SELECT  fac.FACILITYNAME ||','||fac.ADDRESS1 ||','||fac.City||','||fac.STATE ||','||fac.ZIPCODE ||','||fac.COUNTY ,
db2gse.ST_Distance(db2gse.st_point(-72.993983,40.824369,1),GEOLOCATION) AS dist
FROM CSE532.FACILITY AS fac,CSE532.FACILITYCERTIFICATION AS fc
WHERE  fac.FACILITYID=fc.FACILITYID AND fc.ATTRIBUTEVALUE ='Emergency Department' 
AND db2gse.ST_Within(db2gse.st_point(-72.993983,40.824369,1),db2gse.ST_Buffer(GEOLOCATION,10,'KILOMETER'));
SELECT CURRENT TIMESTAMP FROM SYSIBM.SYSDUMMY1;